app:
  title: 'Phalcon Website'
  name: 'Phalcon Website'
  author: 'Phalcon Team'
  description: 'Official Phalcon Documentation'
  keywords: 'php, phalcon, phalcon php, php framework, faster php framework, php extension, next generation framework, docs, documentation'
  email: 'team@phalcon.io'

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - serve



